
name: on-baording-CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install/Lint/Test server dependencies
        run: |
          cd server
          npm install
          npm run lint
          npm test
          
      - name: Install client dependencies
        run: |
          cd client
          npm install
          npm run lint
          npm test

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Build Docker Image
      #   run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/on-boarding:${{ github.sha }}

      # - name: Push Dokcer Image
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME}}/on-boarding:${{ github.sha }}
